export const AUDIT_SCHEMA_VERSION = "1" as const;
export const AUDIT_MODE = "OFFLINE_AUDIT_TIMELINE" as const;

export const AUDIT_SOURCE_KINDS = Object.freeze([
  "DEMO_AUDIT",
  "VALIDATED_SIGNED_FLOW",
  "EXECUTOR_RESULT",
  "LOCAL_CONTRACT_EVIDENCE",
  "ARC_DEPLOYMENT_EVIDENCE",
] as const);

export const NORMALIZED_EVENT_TYPES = Object.freeze([
  "PROPOSAL_CREATED",
  "POLICY_DECISION_RECORDED",
  "SIGNED_AUTHORIZATION_CREATED",
  "EXECUTOR_REQUEST_PREPARED",
  "TRANSPORT_SIMULATION_ACCEPTED",
  "TRANSPORT_SUBMISSION_ACCEPTED",
  "SIMULATED_SUBMISSION_REFERENCE_RECORDED",
  "TRANSACTION_SUBMISSION_RECORDED",
  "EXECUTION_EVIDENCE_VERIFIED",
  "SETTLEMENT_EVIDENCE_RECORDED",
  "REPLAY_REJECTED",
  "INDIRECT_PROMPT_INJECTION_REJECTED",
  "DIRECT_VAULT_BYPASS_REJECTED",
  "NON_ISSUER_REVOCATION_REJECTED",
  "REVOCATION_VERIFIED",
  "POST_REVOCATION_EXECUTION_REJECTED",
  "LOCAL_DEPLOYMENT_EVIDENCE_VERIFIED",
  "LOCAL_VAULT_FUNDING_EVIDENCE_VERIFIED",
  "ARC_DEPLOYMENT_EVIDENCE_VERIFIED",
] as const);

export const LIFECYCLE_STAGES = Object.freeze([
  "PROPOSAL",
  "POLICY_DECISION",
  "SIGNED_AUTHORIZATION",
  "TRANSPORT_PREPARATION",
  "TRANSPORT_ACCEPTANCE",
  "TRANSACTION_SUBMISSION",
  "EXECUTION_EVIDENCE",
  "SETTLEMENT_EVIDENCE",
  "SECURITY_CONTROL",
  "REVOCATION",
  "DEPLOYMENT_EVIDENCE",
] as const);

export const EVIDENCE_CLASSES = Object.freeze([
  "OBSERVATIONAL_DEMO_AUDIT",
  "VERIFIED_SIGNED_ARTIFACT",
  "VERIFIED_POLICY_OUTPUT",
  "SIMULATED_TRANSPORT_OUTPUT",
  "EXECUTOR_TRANSPORT_OUTPUT",
  "LOCAL_EVM_RECEIPT_STATE_EVIDENCE",
  "COMMITTED_ARC_DEPLOYMENT_EVIDENCE",
  "DERIVED_SECURITY_SCENARIO_EVIDENCE",
] as const);

export const EVENT_OUTCOMES = Object.freeze([
  "OBSERVED",
  "APPROVED",
  "REJECTED",
  "ACCEPTED",
  "VERIFIED",
] as const);

export const CLAIM_SCOPES = Object.freeze([
  "PROPOSAL_ONLY",
  "POLICY_DECISION_ONLY",
  "SIGNED_AUTHORIZATION_ONLY",
  "AUTHORIZED_REQUEST_PREPARATION_ONLY",
  "SIMULATED_TRANSPORT_ACCEPTANCE_ONLY",
  "EXECUTOR_TRANSPORT_ACCEPTANCE_ONLY",
  "SIMULATED_SUBMISSION_REFERENCE_ONLY",
  "LOCAL_ANVIL_TRANSACTION_SUBMISSION",
  "LOCAL_ANVIL_EXECUTION_EVIDENCE",
  "LOCAL_ANVIL_SETTLEMENT_OBSERVATION",
  "LOCAL_ANVIL_REPLAY_REJECTION",
  "FIXED_COMPROMISED_PROPOSER_REJECTION",
  "LOCAL_ANVIL_DIRECT_BYPASS_REJECTION",
  "LOCAL_ANVIL_NON_ISSUER_REVOCATION_REJECTION",
  "LOCAL_ANVIL_REVOCATION_EVIDENCE",
  "LOCAL_ANVIL_POST_REVOCATION_REJECTION",
  "LOCAL_ANVIL_DEPLOYMENT_EVIDENCE",
  "LOCAL_ANVIL_FUNDING_EVIDENCE",
  "ARC_DEPLOYMENT_TRANSACTION_ONLY",
] as const);

export const TRACK_RANK = Object.freeze({
  DEPLOYMENT: 1,
  PAYMENT_FLOW: 2,
  SECURITY_CONTROL: 3,
  REVOCATION: 4,
});

export const STAGE_RANK = Object.freeze({
  DEPLOYMENT_EVIDENCE: 1,
  PROPOSAL: 2,
  POLICY_DECISION: 3,
  SIGNED_AUTHORIZATION: 4,
  TRANSPORT_PREPARATION: 5,
  TRANSPORT_ACCEPTANCE: 6,
  TRANSACTION_SUBMISSION: 7,
  EXECUTION_EVIDENCE: 8,
  SETTLEMENT_EVIDENCE: 9,
  SECURITY_CONTROL: 10,
  REVOCATION: 11,
});

export const SOURCE_KIND_RANK = Object.freeze({
  ARC_DEPLOYMENT_EVIDENCE: 1,
  LOCAL_CONTRACT_EVIDENCE: 2,
  VALIDATED_SIGNED_FLOW: 3,
  DEMO_AUDIT: 4,
  EXECUTOR_RESULT: 5,
});
